# Generated by Django 3.2.9 on 2022-06-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20220624_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='country',
            field=models.CharField(max_length=50, null=True, verbose_name='国'),
        ),
    ]
