# Generated by Django 3.2.9 on 2022-05-14 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='subimage',
            field=models.ImageField(default=datetime.datetime(2022, 5, 14, 11, 30, 45, 804062, tzinfo=utc), upload_to='images', verbose_name='コンテンツ画像'),
            preserve_default=False,
        ),
    ]
