# Generated by Django 3.1.13 on 2021-09-12 04:08

from django.db import migrations, models
import programing.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to=programing.models.load_path_video)),
                ('thum', models.ImageField(upload_to=programing.models.load_path_thum)),
                ('summary', models.CharField(max_length=255)),
            ],
        ),
    ]
