# Generated by Django 3.2.9 on 2022-02-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220128_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='有効期限'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='顧客ID'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
